-- MySQL Script generated by MySQL Workbench
-- Mon Jan 11 13:51:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`films`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`films` ;

CREATE TABLE IF NOT EXISTS `mydb`.`films` (
  `movie_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `duration` INT NULL,
  `publication_year` DATE NULL,
  `cover_image` VARBINARY(8000) NULL,
  `previous_part` INT NOT NULL,
  `price` DECIMAL(5,2) NULL,
  `URL` VARCHAR(255) NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gebruikers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gebruikers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`gebruikers` (
  `emailadres` VARCHAR(90) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `abbonement` INT NULL,
  `startDatumSub` DATE NULL,
  `endDatumsSub` DATE NULL,
  `username` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(45) NOT NULL,
  `land` VARCHAR(45) NOT NULL,
  `geslacht` VARCHAR(45) NOT NULL,
  `geboortedatum` DATE NOT NULL,
  PRIMARY KEY (`emailadres`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Content` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Content` (
  `content_id` INT NOT NULL,
  `pagina_id` INT NOT NULL,
  `text` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`content_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persoon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Persoon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Persoon` (
  `persoon_id` INT NOT NULL,
  `voornaam` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `geslacht` VARCHAR(45) NULL,
  PRIMARY KEY (`persoon_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cast` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cast` (
  `movie_id` INT NOT NULL,
  `persoon_id` INT NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`movie_id`, `persoon_id`),
  INDEX `FK_persooncast_idx` (`persoon_id` ASC) VISIBLE,
  CONSTRAINT `FK_moviecast`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`films` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_persooncast`
    FOREIGN KEY (`persoon_id`)
    REFERENCES `mydb`.`Persoon` (`persoon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Regisseur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Regisseur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Regisseur` (
  `movie_id` INT NOT NULL,
  `persoon_id` INT NOT NULL,
  PRIMARY KEY (`movie_id`, `persoon_id`),
  INDEX `FK_persoonregisseur_idx` (`persoon_id` ASC) VISIBLE,
  CONSTRAINT `FK_filmregisseur`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`films` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_persoonregisseur`
    FOREIGN KEY (`persoon_id`)
    REFERENCES `mydb`.`Persoon` (`persoon_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `genre_name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`genre_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filmgenre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`filmgenre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`filmgenre` (
  `movie_id` INT NOT NULL,
  `genre_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`movie_id`, `genre_name`),
  INDEX `FK_genre_idx` (`genre_name` ASC) VISIBLE,
  CONSTRAINT `FK_genre`
    FOREIGN KEY (`genre_name`)
    REFERENCES `mydb`.`genre` (`genre_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`films` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`watchhistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`watchhistory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`watchhistory` (
  `emailadres` VARCHAR(90) NOT NULL,
  `movie_id` INT NOT NULL,
  `watchdate` DATE NULL,
  PRIMARY KEY (`emailadres`, `movie_id`),
  INDEX `FK_film_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `FK_film`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`films` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_gebruikers`
    FOREIGN KEY (`emailadres`)
    REFERENCES `mydb`.`gebruikers` (`emailadres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
